<!DOCTYPE html>
<html>
    <head>
        <title>Two-Factor Authentication Demo</title>
        <meta charset="utf-8"/>
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet"/>
        <link href="//netdna.bootstrapcdn.com/bootswatch/2.3.0/cosmo/bootstrap.min.css" rel="stylesheet"/>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script src="jquery.qrcode-0.2.min.js"></script>
        <script type="text/javascript">
            jQuery(function ($) {
                $('#frmValidation').submit(function (event) {
                    event.preventDefault();

                    $('#lblReturn').text('');
                    $('#controlGroup').removeClass('error').removeClass('success');


                    $.post("", {
                        "method": "validate",
                        "uri": $('#inputURI').val(),
                        "otp": $('#inputCode').val()
                    }, function (response) {
                        if (response.success) {
                            if (response.data.valid) {
                                $('#lblReturn').text('Code is valid');
                                $('#controlGroup').addClass('success');
                            } else {
                                $('#lblReturn').text('Invalid code');
                                $('#controlGroup').addClass('error')
                            }
                        } else {
                            alert(response.exception.class + ': ' + response.exception.message);
                        }

                    }, 'json');
                });

                var previousMs = 0;
                var timeStep =
                <?php echo $totp->getTimeStep(); ?> *
                1000;

                var updateProgressBar = function () {
                    var currentMs = (new Date()).getTime() % timeStep;

                    $('#bar').css('width', Math.floor((currentMs / timeStep) * 100) + '%');

                    if (currentMs < previousMs) {
                        $('#lblCode').parent().animate({
                            'opacity': 0
                        }, 500, 'swing', function () {
                            $.post("", {
                                "method": "generate",
                                "uri": $('#inputURI').val()
                            }, function (response) {
                                if (response.success) {
                                    $('#lblCode').text(response.data.otp);

                                    $('#lblCode').parent().animate({
                                        'opacity': 1
                                    }, 500, 'swing');
                                } else {
                                    alert(response.exception.class + ': ' + response.exception.message);
                                }
                            }, 'json');
                        });
                    }

                    previousMs = currentMs;
                };

                updateProgressBar();
                setInterval(updateProgressBar, 100);

                $('#divQRCode').qrcode({
                    render: 'div',
                    width: 242,
                    height: 242,
                    text: $('#inputURI').val()
                })
            });
        </script>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-static-top">
            <div class="navbar-inner">
                <a class="brand" href="">SLT\GoogleAuthenticator</a>

                <ul class="nav">
                    <li class="active"><a href=""><i class="icon-cog"></i> Demo</a></li>
                    <li><a href="#"><i class="icon-briefcase icon-white"></i> Packagist</a></li>
                    <li><a href="http://www.sidleetechnologies.com/"><i class="icon-globe icon-white"></i> Sid Lee
                            Technologies</a></li>
                </ul>
            </div>
        </div>

        <div class="container">
            <div class="page-header">
                <h1>Google Authenticator Demo</h1>
            </div>

            <div class="row">
                <div class="span4">
                    <div class="well">
                        <h2>Generated Token</h2>

                        <p class="text-center">
                            <span class="badge badge-info">Label: <?php echo htmlentities(
                                    $totp->getLabel(),
                                    ENT_QUOTES,
                                    'UTF-8'
                                ); ?></span>
                        </p>

                        <p class="text-center">
                            <span class="badge badge-success">Code: <span id="lblCode"><?php echo htmlentities(
                                        $totp->calculate(),
                                        ENT_QUOTES,
                                        'UTF-8'
                                    ); ?></span></span>
                        </p>

                        <div class="progress">
                            <div id="bar" class="bar"></div>
                        </div>

                        <div class="img-rounded" style="background: white; padding: 10px;">
                            <div id="divQRCode"></div>
                        </div>
                    </div>
                </div>

                <div class="span8">
                    <div style="padding: 19px">
                        <h2>Validation</h2>

                        <form id="frmValidation" class="form-horizontal" method="POST">
                            <div class="control-group" id="controlGroup">
                                <label class="control-label" for="inputCode">Code:</label>

                                <div class="controls">
                                    <input type="text" name="otp" autocomplete="off" id="inputCode"
                                           placeholder="6 digit number"/>

                                    <div class="help-inline" id="lblReturn"></div>

                                    <input type="hidden" id="inputURI" name="uri" value="<?php echo htmlentities(
                                        $totp->toUri(),
                                        ENT_QUOTES,
                                        'UTF-8'
                                    ); ?>"/>
                                </div>
                            </div>

                            <div class="form-actions">
                                <button class="btn btn-primary" type="submit">Validate</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </body>
</html>